import { StyleSheet } from 'react-native';

export const colors = {
  background: '#020617', card: '#0f172a', border: '#1e293b', text: '#f8fafc', muted: '#cbd5e1', subtle: '#94a3b8',
  primary: '#047857', accent: '#34d399', danger: '#be123c', dangerText: '#fda4af', warning: '#fbbf24', income: '#34d399', expense: '#fb7185',
};

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.background },
  content: { padding: 16, gap: 12, paddingBottom: 48 },
  title: { color: colors.text, fontSize: 20, fontWeight: '700' },
  muted: { color: colors.muted, fontSize: 14, lineHeight: 20 },
  strongText: { color: colors.text, fontSize: 15, fontWeight: '700' },
  box: { backgroundColor: colors.card, borderColor: colors.border, borderWidth: 1, borderRadius: 12, padding: 14, gap: 8 },
  warningBox: { borderColor: colors.warning },
  dangerBox: { borderColor: colors.dangerText },
  button: { backgroundColor: colors.primary, borderRadius: 10, paddingVertical: 12, paddingHorizontal: 16, alignItems: 'center', minHeight: 48, justifyContent: 'center' },
  secondary: { backgroundColor: '#1e293b' },
  danger: { backgroundColor: colors.danger },
  dim: { opacity: 0.6 },
  buttonText: { color: '#fff', fontSize: 16, fontWeight: '600' },
  field: { gap: 6 },
  label: { color: colors.text, fontSize: 15 },
  input: { borderWidth: 1, borderColor: '#64748b', backgroundColor: colors.card, color: '#fff', borderRadius: 8, padding: 12, fontSize: 16 },
  inputError: { borderColor: colors.dangerText },
  error: { color: colors.dangerText, fontSize: 14 },
  chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  chip: { borderWidth: 1, borderColor: '#64748b', borderRadius: 20, paddingVertical: 8, paddingHorizontal: 14, minHeight: 40, justifyContent: 'center' },
  chipSelected: { backgroundColor: colors.primary, borderColor: colors.accent },
  chipText: { color: colors.text, fontSize: 15 },
  line: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 12 },
  lineLabel: { color: colors.muted, fontSize: 15, flexShrink: 1 },
  lineValue: { color: colors.text, fontSize: 15, fontVariant: ['tabular-nums'] },
  strong: { color: colors.text, fontWeight: '700', fontSize: 17 },
  missing: { color: colors.warning },
  barRow: { gap: 4 },
  barTrack: { height: 8, borderRadius: 4, backgroundColor: colors.border, overflow: 'hidden' },
  barFill: { height: 8 },
  center: { alignItems: 'center', gap: 8, padding: 24 },
  monthBar: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  monthButton: { minWidth: 48, minHeight: 48, alignItems: 'center', justifyContent: 'center' },
  monthArrow: { color: colors.accent, fontSize: 28 },
  monthLabel: { color: colors.text, fontSize: 18, fontWeight: '700', textTransform: 'capitalize' },
  badge: { alignSelf: 'flex-start', color: '#111827', backgroundColor: colors.warning, borderRadius: 6, paddingHorizontal: 6, paddingVertical: 2, fontSize: 12, overflow: 'hidden' },
  badgeDanger: { backgroundColor: colors.dangerText },
  badgeOk: { backgroundColor: colors.accent },
  notice: { color: colors.accent, fontSize: 15 },
  item: { flexDirection: 'row', alignItems: 'center', gap: 12, backgroundColor: colors.card, borderColor: colors.border, borderWidth: 1, borderRadius: 10, padding: 12, minHeight: 56 },
  itemMain: { flex: 1, gap: 2 },
  itemTitle: { color: colors.text, fontSize: 16 },
  itemRight: { color: colors.text, fontSize: 15, fontVariant: ['tabular-nums'] },
});
