import { randomUUID } from 'node:crypto';
import { test,expect,type APIRequestContext } from '@playwright/test';
import { TEST_PASSWORD } from './credentials';
import { e2eDatabase } from './database';
import { clearTestCollections } from '../../packages/db/tests/firestore-fixture';
import { accountBalances,monthTotals,moneyToCents } from '../../packages/shared/src';
const db=e2eDatabase(),origin='http://127.0.0.1:3000';
test.setTimeout(90000);
test.beforeEach(async()=>{await clearTestCollections(db,['authRateLimits']);});
test.afterAll(async()=>{await db.firestore.terminate();});
async function login(request:APIRequestContext,email='a@example.test') {expect((await request.post('/api/auth/sign-in/email',{headers:{origin},data:{email,password:TEST_PASSWORD}})).status()).toBe(200);}
const headers=()=>({origin,'idempotency-key':randomUUID()});
async function refs(request:APIRequestContext,name:string) {
  const a=await request.post('/api/accounts',{headers:headers(),data:{name,type:'carteira',openingBalance:'1000.00',openingDate:'2000-01-01'}}),c=await request.post('/api/categories',{headers:headers(),data:{name:'Cartão '+name,color:'#336699'}});expect(a.status()).toBe(201);expect(c.status()).toBe(201);return {accountId:(await a.json()).id,categoryId:(await c.json()).id};
}
async function invoice(request:APIRequestContext,card:string,month:string) {const r=await request.get('/api/cards/'+card+'/invoices/'+month);expect(r.status()).toBe(200);return r.json();}
async function newCard(request:APIRequestContext,name:string,account:string) {const r=await request.post('/api/cards',{headers:headers(),data:{name,paymentAccountId:account,closingDay:25,dueDay:5}});expect(r.status()).toBe(201);return (await r.json()).id;}
async function purchase(request:APIRequestContext,card:string,month:string,category:string,name:string) {const r=await request.post('/api/cards/'+card+'/purchases',{headers:headers(),data:{description:name,categoryId:category,totalAmount:'100.00',count:1,purchaseDate:month+'-20',firstMonth:month,confirmed:true}});expect(r.status()).toBe(201);return r.json();}
test('reviews 300 in three installments, separates invoice payment from expense and preserves card history',async({page},info)=>{
  await login(page.request);const name='Parcelado '+info.project.name+' '+Date.now(),reference=await refs(page.request,name),month=({chromium:'2040-01',webkit:'2040-04','mobile-web':'2040-07'})[info.project.name]!;
  await page.goto('/cards?mes='+month);await page.getByRole('button',{name:'Novo cartão',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Novo cartão',exact:true});
  await dialog.getByLabel('Nome do cartão',{exact:true}).fill(name);await dialog.getByLabel('Conta de pagamento',{exact:true}).selectOption(reference.accountId);await dialog.getByLabel('Dia de fechamento',{exact:true}).fill('25');await dialog.getByLabel('Dia de vencimento',{exact:true}).fill('5');await dialog.getByRole('button',{name:'Salvar cartão',exact:true}).click();await expect(dialog).toHaveCount(0);
  const cardsResponse=await page.request.get('/api/cards');expect(cardsResponse.status()).toBe(200);const card=(await cardsResponse.json()).cards.find((c:{name:string})=>c.name===name).id;
  await page.getByLabel('Cartão',{exact:true}).selectOption(card);await page.getByRole('button',{name:'Registrar compra / parcelas',exact:true}).click();const buy=page.getByRole('dialog',{name:'Compra e parcelamento',exact:true});
  await buy.getByLabel('Descrição',{exact:true}).fill(name);await buy.getByLabel('Categoria',{exact:true}).selectOption(reference.categoryId);await buy.getByLabel('Valor total da compra (R$)',{exact:true}).fill('300,00');await buy.getByLabel('Número de parcelas',{exact:true}).fill('3');await buy.getByLabel('Data da compra',{exact:true}).fill(month+'-28');await buy.getByRole('button',{name:'Revisar parcelas',exact:true}).click();await expect(buy.getByRole('list',{name:'Parcelas para confirmação'})).toContainText('3 ·');
  await buy.getByLabel('Confirmo o valor total, as parcelas e as competências informadas.',{exact:true}).check();await buy.getByRole('button',{name:'Confirmar compra',exact:true}).click();await expect(buy).toHaveCount(0);
  let view=await invoice(page.request,card,month);expect(view.entries).toHaveLength(1);expect(view.totals.computed).toBe('100.00');
  await page.getByRole('button',{name:'Revisar fatura',exact:true}).click();const review=page.getByRole('dialog',{name:'Revisar fatura',exact:true});await review.getByLabel('Total informado na fatura (R$)',{exact:true}).fill('100,00');await review.getByLabel('Fatura recebida / fechada',{exact:true}).check();await review.getByRole('button',{name:'Salvar fatura',exact:true}).click();await expect(review).toHaveCount(0);
  await page.getByRole('button',{name:'Pagar fatura',exact:true}).click();const pay=page.getByRole('dialog',{name:'Pagar fatura',exact:true});await pay.getByLabel('Valor pago (R$)',{exact:true}).fill('40,00');await pay.getByLabel('Data de pagamento',{exact:true}).fill(month+'-28');await pay.getByLabel('Categoria do pagamento',{exact:true}).selectOption(reference.categoryId);await pay.getByLabel('Confirmo a saída da conta de pagamento e a conciliação selecionada.',{exact:true}).check();await pay.getByRole('button',{name:'Confirmar pagamento da fatura',exact:true}).click();await expect(pay).toHaveCount(0);
  view=await invoice(page.request,card,month);expect(view).toMatchObject({status:'partial',totals:{computed:'100.00',payments:'40.00',remaining:'60.00',divergence:'0.00'}});
  const account=(await db.get('accounts',reference.accountId))!,entries=await db.owned('transactions',account.ownerId,{where:[{field:'accountId',value:reference.accountId}]});expect(entries.filter(e=>e.kind==='expense')).toHaveLength(3);expect(monthTotals(entries,month).expenses).toBe(10000n);expect(accountBalances([account],entries,month+'-28').get(account.id)).toBe(96000n);
  await page.getByRole('button',{name:'Editar cartão',exact:true}).click();const edit=page.getByRole('dialog',{name:'Editar cartão',exact:true});await edit.getByLabel('Dia de fechamento',{exact:true}).fill('31');await edit.getByRole('button',{name:'Salvar cartão',exact:true}).click();await expect(edit).toHaveCount(0);expect((await invoice(page.request,card,month)).closingDate).toBe(month+'-25');
  await page.screenshot({path:'test-results/cards-'+info.project.name+'.png',fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
  await page.getByRole('button',{name:'Arquivar cartão',exact:true}).click();await expect(page.getByRole('button',{name:'Registrar compra / parcelas',exact:true})).toBeDisabled();await page.getByRole('button',{name:'Restaurar cartão',exact:true}).click();await expect(page.getByRole('button',{name:'Registrar compra / parcelas',exact:true})).toBeEnabled();
});
test('reconciles an imported duplicate, refunds part of an installment and exposes invoice divergence in the UI',async({page},info)=>{
  await login(page.request);const name='Estorno '+info.project.name+' '+Date.now(),reference=await refs(page.request,name),month=({chromium:'2041-01',webkit:'2041-03','mobile-web':'2041-05'})[info.project.name]!,card=await newCard(page.request,name,reference.accountId);await purchase(page.request,card,month,reference.categoryId,name);
  const response=await page.request.post('/api/entries',{headers:headers(),data:{...reference,description:name+' importado',amount:'100.00',kind:'expense',status:'recorded',purchaseDate:month+'-20',competenceMonth:month+'-01',dueDate:null,paidDate:null}});expect(response.status()).toBe(201);const saved=await response.json(),source=(await db.get('transactions',saved.id))!;await db.put('transactions',{...source,source:'csv'});
  await page.goto('/cards?mes='+month+'&card='+card);await page.getByRole('button',{name:'Conciliar compra',exact:true}).click();const reconcile=page.getByRole('dialog',{name:'Conciliar compra ou duplicata',exact:true});await reconcile.getByRole('button',{name:'Carregar despesas para conciliar',exact:true}).click();await reconcile.getByLabel('Despesa de origem',{exact:true}).selectOption(source.id);const before=await invoice(page.request,card,month);await reconcile.getByLabel('Destino na fatura',{exact:true}).selectOption(before.entries[0].id);await reconcile.getByLabel('Revisei a competência e confirmo a reclassificação ou remoção da duplicata.',{exact:true}).check();await reconcile.getByRole('button',{name:'Confirmar conciliação da compra',exact:true}).click();await expect(reconcile).toHaveCount(0);expect((await invoice(page.request,card,month)).totals.computed).toBe('100.00');
  await page.getByRole('button',{name:'Adicionar encargo / crédito',exact:true}).click();const refund=page.getByRole('dialog',{name:'Encargo, crédito ou estorno',exact:true});await refund.getByLabel('Tipo',{exact:true}).selectOption('refund');await refund.getByLabel('Descrição',{exact:true}).fill('Estorno parcial');await refund.getByLabel('Valor (R$)',{exact:true}).fill('25,00');await refund.getByLabel('Data do item',{exact:true}).fill(month+'-28');await refund.getByLabel('Compra original',{exact:true}).selectOption(before.entries[0].id);await refund.getByRole('button',{name:'Confirmar item',exact:true}).click();await expect(refund).toHaveCount(0);
  const after=await invoice(page.request,card,month);expect(after.totals).toMatchObject({computed:'75.00',credits:'25.00'});expect(monthTotals(await db.owned('transactions',source.ownerId,{where:[{field:'accountId',value:reference.accountId}]}),month).expenses).toBe(7500n);
  await page.getByRole('button',{name:'Revisar fatura',exact:true}).click();const review=page.getByRole('dialog',{name:'Revisar fatura',exact:true});await review.getByLabel('Total informado na fatura (R$)',{exact:true}).fill('100,00');await review.getByRole('button',{name:'Salvar fatura',exact:true}).click();await expect(review).toHaveCount(0);await expect(page.getByRole('alert').filter({hasText:'Fatura divergente'})).toBeVisible();await page.reload();await expect(page.getByRole('region',{name:'Itens da fatura'})).toContainText('duplicata(s) conciliada(s)');expect((await db.get('transactions',source.id))!.reconciledIntoId).toBe(before.entries[0].id);
});
test('links a forecast to a card purchase, reconciles a bank payment once and denies foreign or unreviewed writes',async({request,playwright},info)=>{
  expect((await request.get('/api/cards')).status()).toBe(401);expect((await request.get('/api/invoices/'+randomUUID()+'/candidates')).status()).toBe(401);expect((await request.post('/api/cards',{headers:headers(),data:{}})).status()).toBe(401);
  await login(request);const name='Vínculo '+info.project.name+' '+Date.now(),reference=await refs(request,name),month=({chromium:'2042-01',webkit:'2042-03','mobile-web':'2042-05'})[info.project.name]!,card=await newCard(request,name,reference.accountId);await purchase(request,card,month,reference.categoryId,name);
  const rule=await request.post('/api/recurrences',{headers:headers(),data:{fromMonth:month,schedule:{...reference,description:name,amount:'110.00',startDate:month+'-01',endDate:month+'-28',dueDay:28,estimated:true,reminderDays:null,paused:false}}});expect(rule.status()).toBe(201);const ruleId=(await rule.json()).id;expect((await request.post('/api/planning/'+month+'/generate',{headers:headers(),data:{}})).status()).toBe(200);
  const planned=await request.get('/api/planning/'+month);expect(planned.status()).toBe(200);const before=await planned.json(),occurrence=before.occurrences.find((o:{ruleId:string})=>o.ruleId===ruleId),view=await invoice(request,card,month),entry=view.entries[0];
  expect((await request.post('/api/invoices/'+view.id+'/occurrence',{headers:{...headers(),'if-match':view.revision},data:{transactionId:entry.id,transactionRevision:entry.revision,occurrenceId:occurrence.id,occurrenceRevision:occurrence.revision,confirmed:true}})).status()).toBe(200);
  const afterResponse=await request.get('/api/planning/'+month);expect(afterResponse.status()).toBe(200);const after=await afterResponse.json();expect(moneyToCents(before.summary.pending)-moneyToCents(after.summary.pending)).toBe(11000n);
  const bankResponse=await request.post('/api/entries',{headers:headers(),data:{...reference,description:'Pagamento bancário',amount:'100.00',kind:'expense',status:'settled',purchaseDate:month+'-28',competenceMonth:month+'-01',dueDate:null,paidDate:month+'-28'}});expect(bankResponse.status()).toBe(201);const bank=await bankResponse.json(),current=await invoice(request,card,month),h={...headers(),'if-match':current.revision},payload={amount:'100.00',paidDate:month+'-28',categoryId:reference.categoryId,transactionId:bank.id,transactionRevision:bank.revision,confirmed:true};
  const responses=await Promise.all([1,2].map(()=>request.post('/api/invoices/'+current.id+'/pay',{headers:h,data:payload})));for(const r of responses)expect(r.status()).toBe(200);expect((await invoice(request,card,month)).totals.remaining).toBe('0.00');expect((await db.get('transactions',bank.id))!.kind).toBe('adjustment');
  const foreign=await playwright.request.newContext();await login(foreign,'b@example.test');try{expect((await foreign.get('/api/cards/'+card+'/invoices/'+month)).status()).toBe(404);expect((await foreign.post('/api/invoices/'+current.id+'/pay',{headers:h,data:payload})).status()).toBe(404);}finally{await foreign.dispose();}
  expect((await request.post('/api/cards/'+card+'/purchases',{headers:{...headers(),origin:'https://hostile.test'},data:{}})).status()).toBe(403);expect((await request.get('/api/cards/'+card+'/invoices/invalid')).status()).toBe(400);expect((await request.post('/api/invoices/'+current.id+'/pay',{headers:{...headers(),'if-match':current.revision},data:{...payload,confirmed:false}})).status()).toBe(400);
});
