'use client';
import { useState,type FormEvent } from 'react';
import { civilToday,type CardRecord,type InvoiceView } from '@ecofinance/shared';
import { FinanceDialog } from '@/components/finance-dialog';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { usePlanningSave,selectClass,moneyText,planningMoney,type PlanningReferences } from '../planning/planning-client-utils';
import { CardSelect,CardAmount,CardDate } from './card-fields';
import { useRefundPurchases } from './card-client-utils';
export function ItemDialog({card,invoice,refs,onClose,onSaved}:{card:CardRecord;invoice:InvoiceView;refs:PlanningReferences;onClose:()=>void;onSaved:()=>void}) {
  const mutation=usePlanningSave(onSaved),[today]=useState(()=>civilToday(new Date())),[type,setType]=useState('interest'),[selected,setSelected]=useState(''),purchases=useRefundPurchases(card.id,invoice.entries),original=purchases.entries.find(e=>e.id===selected);
  const [sourceMonth,setSourceMonth]=useState(invoice.month);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);await mutation.save('/api/invoices/'+invoice.id+'/items','POST',{type,description:String(f.get('description')),amount:moneyText(f.get('amount')),categoryId:type==='refund'?original?.categoryId:String(f.get('categoryId')),purchaseDate:String(f.get('purchaseDate')),competenceMonth:type==='refund'?original?.competenceMonth.slice(0,7):String(f.get('competenceMonth')),refundOfId:type==='refund'?selected:null},invoice.revision);}
  const busy=mutation.busy||purchases.loading;
  return <FinanceDialog title="Encargo, crédito ou estorno" busy={busy} onClose={onClose}><form className="space-y-4" onSubmit={submit}>{(mutation.error||purchases.error)&&<p role="alert">{mutation.error||purchases.error}</p>}<label className="block text-sm">Tipo<select aria-label="Tipo" className={selectClass} value={type} onChange={e=>setType(e.target.value)}><option value="interest">Juros</option><option value="fee">Tarifa</option><option value="credit">Crédito / abatimento</option><option value="refund">Estorno de despesa</option></select></label><label className="block text-sm">Descrição<Input name="description" maxLength={500} required/></label><CardAmount label="Valor (R$)"/><CardDate label="Data do item" name="purchaseDate" value={today}/>{type==='refund'?<><label className="block text-sm">Competência da compra original<Input type="month" value={sourceMonth} onChange={e=>setSourceMonth(e.target.value)}/></label><Button type="button" variant="outline" disabled={busy} onClick={()=>{setSelected('');purchases.load(sourceMonth);}}>Carregar compras originais</Button><label className="block text-sm">Compra original<select aria-label="Compra original" className={selectClass} value={selected} onChange={e=>setSelected(e.target.value)} required><option value="">Selecione</option>{purchases.entries.filter(e=>e.kind==='expense').map(e=><option key={e.id} value={e.id}>{e.description} · {planningMoney(e.amount)}{e.installmentNumber?' · parcela '+e.installmentNumber:''}</option>)}</select></label><p className="text-sm text-muted">O estorno reduz a despesa na competência e categoria originais e credita a fatura atual. Reabra o mês original se estiver fechado. Não é entrada de dinheiro na conta bancária.</p></>:<><CardSelect label="Categoria" name="categoryId" rows={refs.categories}/><CardDate label="Competência da despesa ou abatimento" name="competenceMonth" value={invoice.month} type="month"/><p className="text-sm text-muted">Juros e tarifas aumentam as despesas. Créditos reduzem as despesas na competência escolhida e o saldo da fatura.</p></>}<Button type="submit" disabled={busy||(type==='refund'&&!original)}>Confirmar item</Button></form></FinanceDialog>;
}
