'use client';
import { useState,type FormEvent } from 'react';
import { civilToday,type InvoiceView } from '@ecofinance/shared';
import { FinanceDialog } from '@/components/finance-dialog';
import { Button } from '@/components/ui/button';
import { usePlanningSave,moneyText,selectClass,planningMoney,type PlanningReferences } from '../planning/planning-client-utils';
import { CardSelect,CardAmount,CardDate,CardConfirmation } from './card-fields';
import { useCardCandidates } from './card-client-utils';
export function PaymentDialog({invoice,refs,onClose,onSaved}:{invoice:InvoiceView;refs:PlanningReferences;onClose:()=>void;onSaved:()=>void}) {
  const mutation=usePlanningSave(onSaved),[today]=useState(()=>civilToday(new Date())),[selected,setSelected]=useState(''),candidates=useCardCandidates(invoice.id),candidate=candidates.entries.find(e=>e.id===selected),busy=mutation.busy||candidates.loading;
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);await mutation.save('/api/invoices/'+invoice.id+'/pay','POST',{amount:moneyText(f.get('amount')),paidDate:String(f.get('paidDate')),categoryId:String(f.get('categoryId')),transactionId:candidate?.id??null,transactionRevision:candidate?.revision??null,confirmed:true},invoice.revision);}
  return <FinanceDialog title="Pagar fatura" busy={busy} onClose={onClose}><form className="space-y-4" onSubmit={submit}>{(mutation.error||candidates.error)&&<p role="alert">{mutation.error||candidates.error}</p>}<p className="text-sm text-muted">Saldo calculado {planningMoney(invoice.totals.remaining)}. O pagamento reduz caixa e dívida, sem outra despesa. Pode ser parcial. Para conciliar um pagamento já registrado no banco, escolha a saída com o mesmo valor e data.</p><CardAmount label="Valor pago (R$)" value={invoice.totals.remaining}/><CardDate label="Data de pagamento" name="paidDate" value={today}/><CardSelect label="Categoria do pagamento" name="categoryId" rows={refs.categories}/><Button type="button" variant="outline" disabled={busy} onClick={candidates.load}>Carregar saídas bancárias</Button><label className="block text-sm">Saída bancária existente<select aria-label="Saída bancária existente" className={selectClass} value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Criar pagamento novo</option>{candidates.entries.filter(e=>e.status==='settled').map(e=><option key={e.id} value={e.id}>{e.description} · {planningMoney(e.amount)} · {e.purchaseDate}</option>)}</select></label>{candidates.hasMore&&<p className="text-sm text-muted">Exibindo até 100 candidatos recentes. Consulte os lançamentos para localizar itens mais antigos.</p>}<CardConfirmation label="Confirmo a saída da conta de pagamento e a conciliação selecionada."/><Button type="submit" disabled={busy}>Confirmar pagamento da fatura</Button></form></FinanceDialog>;
}
