'use client';
import { useState,type FormEvent } from 'react';
import { civilToday,cardPurchaseSchema,installmentPlan,type CardRecord } from '@ecofinance/shared';
import { FinanceDialog } from '@/components/finance-dialog';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { usePlanningSave,moneyText,planningMoney,type PlanningReferences } from '../planning/planning-client-utils';
import { CardSelect,CardAmount,CardDate,CardConfirmation } from './card-fields';
export function PurchaseDialog({card,month,refs,onClose,onSaved}:{card:CardRecord;month:string;refs:PlanningReferences;onClose:()=>void;onSaved:()=>void}) {
  const mutation=usePlanningSave(onSaved),[today]=useState(()=>civilToday(new Date())),[preview,setPreview]=useState<{month:string;amount:string;number:number}[]|null>(null),[error,setError]=useState('');
  function data(form:HTMLFormElement,confirmed:boolean) {const f=new FormData(form);return {description:String(f.get('description')),categoryId:String(f.get('categoryId')),totalAmount:moneyText(f.get('totalAmount')),count:Number(f.get('count')),purchaseDate:String(f.get('purchaseDate')),firstMonth:String(f.get('firstMonth')),confirmed};}
  function review(form:HTMLFormElement) {const parsed=cardPurchaseSchema.safeParse(data(form,true));setError(parsed.success?'':'Confira valor, parcelas, categoria e datas.');setPreview(parsed.success?installmentPlan(parsed.data):null);}
  async function submit(event:FormEvent<HTMLFormElement>) {event.preventDefault();await mutation.save('/api/cards/'+card.id+'/purchases','POST',data(event.currentTarget,true));}
  return <FinanceDialog title="Compra e parcelamento" busy={mutation.busy} onClose={onClose}><form className="space-y-4" onSubmit={submit} onChange={event=>{if(!(event.target instanceof HTMLInputElement && event.target.name==='confirmed'))setPreview(null);}}>{(mutation.error||error)&&<p role="alert">{mutation.error||error}</p>}<label className="block text-sm">Descrição<Input name="description" maxLength={500} required/></label><CardSelect label="Categoria" name="categoryId" rows={refs.categories}/><CardAmount label="Valor total da compra (R$)" name="totalAmount"/><label className="block text-sm">Número de parcelas<Input name="count" type="number" min={1} max={24} defaultValue={1} required/></label><CardDate label="Data da compra" name="purchaseDate" value={today}/><CardDate label="Primeira competência" name="firstMonth" value={month} type="month"/><p className="text-sm text-muted">Escolha a primeira competência conforme a fatura. Até 24 parcelas confirmadas; centavos restantes ficam nas primeiras parcelas. O valor total não gera uma despesa adicional.</p><Button type="button" variant="outline" onClick={e=>{const form=e.currentTarget.closest('form');if(form)review(form);}}>Revisar parcelas</Button>{preview&&<ul aria-label="Parcelas para confirmação" className="text-sm space-y-1">{preview.map(p=><li key={p.number}>{p.number} · {p.month} · {planningMoney(p.amount)}</li>)}</ul>}<CardConfirmation label="Confirmo o valor total, as parcelas e as competências informadas."/><Button type="submit" disabled={mutation.busy}>Confirmar compra</Button></form></FinanceDialog>;
}
