'use client';
import { useState,type FormEvent } from 'react';
import type { InvoiceView } from '@ecofinance/shared';
import { FinanceDialog } from '@/components/finance-dialog';
import { Button } from '@/components/ui/button';
import { usePlanningSave,selectClass,planningMoney } from '../planning/planning-client-utils';
import { CardConfirmation } from './card-fields';
import { useCardCandidates } from './card-client-utils';
export function ReconcileDialog({invoice,onClose,onSaved}:{invoice:InvoiceView;onClose:()=>void;onSaved:()=>void}) {
  const mutation=usePlanningSave(onSaved),candidates=useCardCandidates(invoice.id),[sourceId,setSourceId]=useState(''),[targetId,setTargetId]=useState(''),source=candidates.entries.find(e=>e.id===sourceId),target=invoice.entries.find(e=>e.id===targetId),busy=mutation.busy||candidates.loading;
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!source)return;await mutation.save('/api/invoices/'+invoice.id+'/reconcile','POST',{sourceId:source.id,sourceRevision:source.revision,targetId:target?.id??null,targetRevision:target?.revision??null,confirmed:true},invoice.revision);}
  return <FinanceDialog title="Conciliar compra ou duplicata" busy={busy} onClose={onClose}><form className="space-y-4" onSubmit={submit}>{(mutation.error||candidates.error)&&<p role="alert">{mutation.error||candidates.error}</p>}<p className="text-sm text-muted">Selecione uma despesa manual ou importada da conta de pagamento. Vincular como compra retira sua saída de caixa e passa a contar na competência desta fatura. Para uma compra já registrada aqui, selecione-a como destino: a duplicata é arquivada com vínculo de auditoria. Valores devem coincidir.</p><Button type="button" variant="outline" disabled={busy} onClick={candidates.load}>Carregar despesas para conciliar</Button><label className="block text-sm">Despesa de origem<select aria-label="Despesa de origem" className={selectClass} value={sourceId} onChange={e=>setSourceId(e.target.value)} required><option value="">Selecione</option>{candidates.entries.filter(e=>e.kind==='expense').map(e=><option key={e.id} value={e.id}>{e.description} · {planningMoney(e.amount)} · {e.source} · {e.competenceMonth.slice(0,7)}</option>)}</select></label><label className="block text-sm">Destino na fatura<select aria-label="Destino na fatura" className={selectClass} value={targetId} onChange={e=>setTargetId(e.target.value)}><option value="">Vincular como nova compra nesta fatura</option>{invoice.entries.filter(e=>e.kind==='expense').map(e=><option key={e.id} value={e.id}>{e.description} · {planningMoney(e.amount)}{e.installmentNumber?' · parcela '+e.installmentNumber:''}</option>)}</select></label>{candidates.hasMore&&<p className="text-sm text-muted">Exibindo até 100 candidatos recentes.</p>}<CardConfirmation label="Revisei a competência e confirmo a reclassificação ou remoção da duplicata."/><Button type="submit" disabled={busy||!source}>Confirmar conciliação da compra</Button></form></FinanceDialog>;
}
