'use client';
import { useState } from 'react';
import { civilToday,daysBetween,describeDue,type PlanningView,type PlanningOccurrence,type PlanningRule } from '@ecofinance/shared';
import { Button } from '@/components/ui/button';
import { planningMoney } from './planning-client-utils';
import type { OccurrenceAction } from './occurrence-dialog';
export function PlanningList({view,busy,onRule,onOccurrence,onState}:{view:PlanningView;busy:boolean;onRule:(row:PlanningRule)=>void;onOccurrence:(row:PlanningOccurrence,action:OccurrenceAction)=>void;onState:(row:PlanningOccurrence,action:'cancel'|'restore')=>void}) {
  const [today]=useState(()=>civilToday(new Date()));
  return <><section aria-label="Ocorrências do mês" className="space-y-3"><h2 className="text-lg font-semibold">Contas recorrentes do mês</h2>{view.occurrences.length===0&&<p className="text-sm text-muted">Crie uma recorrência e gere as previsões deste mês.</p>}<ul className="grid gap-3 lg:grid-cols-2">{view.occurrences.map(row=>{
    const days=daysBetween(today,row.dueDate),remind=row.reminderDays!==null&&days!==null&&days>=0&&days<=row.reminderDays;
    const status=row.invoiceId?'Conciliada em fatura':({pending:'Pendente',paid:'Paga',postponed:'Adiada',cancelled:'Cancelada'})[row.status],active=row.status==='pending'||row.status==='postponed',disabled=busy||view.closed;
    return <li key={row.id} className="rounded-xl border border-border p-4 space-y-3"><h3 className="font-semibold break-words">{row.description}</h3><p>{planningMoney(row.amount)}{row.estimated?' · Estimado':''} · {status}</p><p className="text-sm text-muted">Vencimento {row.dueDate}{active?' · '+(describeDue(row.dueDate,today)?.label??''):''}</p>{row.overridden&&<p className="text-xs text-muted">Ajuste individual; alterações das próximas preservam este valor.</p>}{active&&remind&&<p className="text-sm text-warning">Lembrete: esta conta vence em {days} dia(s).</p>}{row.transactionId&&<p className="text-xs text-muted">{row.invoiceId?'Previsão conciliada com uma compra; o caixa muda ao pagar a fatura.':'Pagamento conciliado com um único lançamento.'}</p>}
      {row.status!=='paid'&&<div className="flex flex-wrap gap-2">{active&&<><Button disabled={disabled} aria-label={'Pagar '+row.description} onClick={()=>onOccurrence(row,'pay')}>Pagar</Button><Button disabled={disabled} variant="outline" aria-label={'Adiar '+row.description} onClick={()=>onOccurrence(row,'postpone')}>Adiar</Button><Button disabled={disabled} variant="outline" aria-label={'Editar ocorrência '+row.description} onClick={()=>onOccurrence(row,'edit')}>Editar só esta</Button><Button disabled={disabled} variant="outline" aria-label={'Conciliar '+row.description} onClick={()=>onOccurrence(row,'reconcile')}>Conciliar</Button></>}<Button disabled={disabled} variant="ghost" aria-label={(active?'Cancelar ':'Restaurar ')+row.description} onClick={()=>onState(row,active?'cancel':'restore')}>{active?'Cancelar':'Restaurar'}</Button></div>}
    </li>;
  })}</ul></section><section aria-label="Regras de recorrência" className="space-y-3"><h2 className="text-lg font-semibold">Recorrências mensais</h2><p className="text-sm text-muted">Edite ou pause as próximas a partir do mês que escolher. Depois, gere as previsões no mês desejado; repetir a geração não duplica contas.</p><ul className="grid gap-3 lg:grid-cols-2">{view.rules.map(row=><li key={row.id} className="border border-border rounded-xl p-4 space-y-2"><h3 className="font-semibold break-words">{row.description}</h3><p className="text-sm">{planningMoney(row.amount)} · Dia {row.dueDay}{row.paused?' · Pausada':''}</p><Button disabled={busy} variant="outline" aria-label={'Editar próximas '+row.description} onClick={()=>onRule(row)}>Editar / pausar próximas</Button></li>)}</ul></section></>;
}
