import { beforeAll,afterAll,it,expect } from 'vitest';
import { randomUUID,randomBytes } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { collections } from '../src/firestore';
import { testStore,clearTestCollections } from './firestore-fixture';
import { migrateToFirebase,backupFirebase,restoreFirebase,exportPortableFirebase } from '../src/firebase-migration';
import { saveAccount,saveCategory,saveEntry,archiveEntry,revision } from '../../../apps/next/src/lib/manual-finance-service';
import { saveRule,generateMonth } from '../../../apps/next/src/lib/planning-rules';
import { payOccurrence,changeOccurrence } from '../../../apps/next/src/lib/planning-occurrences';
import { loadPlanning,reconciliationCandidates } from '../../../apps/next/src/lib/planning-read';
import { saveBudget,copyPreview,closeMonth } from '../../../apps/next/src/lib/planning-budget';
import { accountBalances,monthlyDueDate } from '../../shared/src';
const db=testStore('planning-'+randomBytes(6).toString('hex')),copy=testStore('planning-copy-'+randomBytes(6).toString('hex'));
const owner='10000000-0000-4000-8000-000000000001',other='20000000-0000-4000-8000-000000000001';
let account:string,category:string,foreign:string;
const accountInput={name:'Planejamento',type:'carteira',openingBalance:'1000.00',openingDate:'2027-01-01'};
function ruleInput(month:string,patch:Record<string,unknown>={}) {return {fromMonth:month,schedule:{accountId:account,categoryId:category,description:'Conta '+month,amount:'100.00',startDate:month+'-01',endDate:monthlyDueDate(month,31),dueDay:31,estimated:false,reminderDays:3,paused:false,...patch}};}
async function occurrence(month:string,ruleId:string) {return (await loadPlanning(db,owner,month)).occurrences.find(o=>o.ruleId===ruleId)!;}
const plan=()=>({limit:'80.00',expectedIncome:'90.00',reserve:'10.00',categories:[{categoryId:category,limit:'70.00'}]});
beforeAll(async()=>{
  await migrateToFirebase(db,JSON.parse(await readFile('packages/db/tests/fixtures/portable-synthetic.json','utf8')));
  await clearTestCollections(db,[...collections.filter(c=>c!=='users'),'_unique','_migration']);
  account=String((await saveAccount(db,owner,randomUUID(),accountInput)).id);category=String((await saveCategory(db,owner,randomUUID(),{name:'Fixas',color:'#112233'})).id);
  foreign=String((await saveAccount(db,other,randomUUID(),{...accountInput,name:'Outro dono'})).id);
});
afterAll(async()=>{for(const store of [db,copy]){await clearTestCollections(store);await store.firestore.terminate();}});
it('generates once under independent concurrent requests and exact replay, including leap February',async()=>{
  const rule=await saveRule(db,owner,randomUUID(),ruleInput('2028-02'));
  const keys=[randomUUID(),randomUUID()];
  const generated=await Promise.all(keys.map(key=>generateMonth(db,owner,key,'2028-02')));
  expect(generated.map(g=>g.created).sort()).toEqual([0,1]);expect(await generateMonth(db,owner,keys[0]!,'2028-02')).toEqual(generated[0]);
  const rows=await db.owned('recurrenceOccurrences',owner,{where:[{field:'ruleId',value:rule.id}]});expect(rows).toHaveLength(1);expect(rows[0]!.dueDate).toBe('2028-02-29');
  expect((await generateMonth(db,owner,randomUUID(),'2028-03')).created).toBe(0);
});
it('pays atomically once and updates settled balances and budget overruns without doubling',async()=>{
  const row=(await loadPlanning(db,owner,'2028-02')).occurrences[0]!,request=randomUUID();
  await saveBudget(db,owner,randomUUID(),'2028-02',plan(),'');
  const before=await loadPlanning(db,owner,'2028-02');expect(before.summary).toMatchObject({realized:'0.00',pending:'100.00',committed:'100.00',remaining:'-20.00',deficit:'20.00'});
  const paid=await Promise.all([1,2].map(()=>payOccurrence(db,owner,request,row.id,row.revision,{amount:'110.10',paidDate:'2028-02-29'})));
  expect(paid[0]).toEqual(paid[1]);
  expect(await db.owned('transactions',owner,{where:[{field:'recurrenceOccurrenceId',value:row.id}]})).toHaveLength(1);
  const after=await loadPlanning(db,owner,'2028-02');expect(after.summary).toMatchObject({realized:'110.10',pending:'0.00',committed:'110.10',remaining:'-30.10',deficit:'30.10'});
  expect(after.categoryTotals[0]!.remaining).toBe('-40.10');
  const entries=await db.owned('transactions',owner);expect(accountBalances([(await db.get('accounts',account))!],entries,'2028-02-29').get(account)).toBe(88990n);
  const latest=after.occurrences[0]!;
  await expect(payOccurrence(db,owner,randomUUID(),latest.id,latest.revision,{amount:'100.00',paidDate:'2028-02-29'})).rejects.toMatchObject({code:'ALREADY_PAID'});
  await expect(payOccurrence(db,owner,request,row.id,row.revision,{amount:'100.00',paidDate:'2028-02-29'})).rejects.toMatchObject({code:'REQUEST_CONFLICT'});
});
it('versions future schedules, preserves paid history and individual postponements, pauses and resumes',async()=>{
  const initial=ruleInput('2027-12',{endDate:'2028-03-31'}),saved=await saveRule(db,owner,randomUUID(),initial);
  for(const month of ['2027-12','2028-01','2028-03'])await generateMonth(db,owner,randomUUID(),month);
  const december=await occurrence('2027-12',String(saved.id));await payOccurrence(db,owner,randomUUID(),december.id,december.revision,{amount:'100.00',paidDate:'2027-12-31'});
  const history=await db.get('recurrenceOccurrences',december.id),january=await occurrence('2028-01',String(saved.id));
  await changeOccurrence(db,owner,randomUUID(),january.id,january.revision,'postpone',{dueDate:'2028-02-05'});
  const edited=await saveRule(db,owner,randomUUID(),{...initial,fromMonth:'2028-01',schedule:{...initial.schedule,description:'Alterada',amount:'150.00'}},String(saved.id),String(saved.revision));
  expect(await db.get('recurrenceOccurrences',december.id)).toEqual(history);
  expect(await occurrence('2028-01',String(saved.id))).toMatchObject({amount:'100.00',dueDate:'2028-02-05',status:'postponed',description:'Conta 2027-12'});
  expect(await occurrence('2028-03',String(saved.id))).toMatchObject({amount:'150.00',description:'Alterada'});
  const paused=await saveRule(db,owner,randomUUID(),{...initial,fromMonth:'2028-03',schedule:{...initial.schedule,paused:true}},String(saved.id),String(edited.revision));
  expect((await occurrence('2028-03',String(saved.id))).status).toBe('cancelled');
  await saveRule(db,owner,randomUUID(),{...initial,fromMonth:'2028-03'},String(saved.id),String(paused.revision));
  const march=await occurrence('2028-03',String(saved.id));expect(march.status).toBe('pending');
  const one=await changeOccurrence(db,owner,randomUUID(),march.id,march.revision,'edit',{description:'Somente março',amount:'99.00',dueDate:'2028-04-01'});
  await changeOccurrence(db,owner,randomUUID(),march.id,String(one.revision),'cancel',{});
  const cancelled=await occurrence('2028-03',String(saved.id));await expect(payOccurrence(db,owner,randomUUID(),march.id,cancelled.revision,{amount:'99.00',paidDate:'2028-03-31'})).rejects.toMatchObject({code:'CANCELLED'});
  await changeOccurrence(db,owner,randomUUID(),march.id,cancelled.revision,'restore',{});expect((await occurrence('2028-03',String(saved.id))).description).toBe('Somente março');
});
it('reconciles an imported movement instead of adding another transaction, with stale and cross-owner checks',async()=>{
  const saved=await saveRule(db,owner,randomUUID(),ruleInput('2029-01'));await generateMonth(db,owner,randomUUID(),'2029-01');
  const row=await occurrence('2029-01',String(saved.id));
  const manual=await saveEntry(db,owner,randomUUID(),{accountId:account,categoryId:category,description:'Importada',amount:'95.50',kind:'expense',status:'recorded',purchaseDate:'2029-01-30',competenceMonth:'2029-01-01',dueDate:null,paidDate:null});
  const entry=(await db.get('transactions',String(manual.id)))!;await db.put('transactions',{...entry,source:'ofx'});
  const candidates=await reconciliationCandidates(db,owner,row.id);expect(candidates.entries.map(e=>e.id)).toContain(entry.id);
  const input={transactionId:entry.id,transactionRevision:revision(entry),paidDate:'2029-01-31'};
  await expect(payOccurrence(db,other,randomUUID(),row.id,row.revision,input,true)).rejects.toMatchObject({code:'NOT_FOUND'});
  await expect(payOccurrence(db,owner,randomUUID(),row.id,row.revision,{...input,transactionRevision:'stale'},true)).rejects.toMatchObject({code:'REVISION_CONFLICT'});
  const count=(await db.owned('transactions',owner)).length,request=randomUUID();await payOccurrence(db,owner,request,row.id,row.revision,input,true);await payOccurrence(db,owner,request,row.id,row.revision,input,true);
  expect((await db.owned('transactions',owner)).length).toBe(count);expect((await db.get('transactions',entry.id))!.recurrenceOccurrenceId).toBe(row.id);
  expect((await loadPlanning(db,owner,'2029-01')).summary).toMatchObject({realized:'95.50',pending:'0.00',committed:'95.50'});
  expect((await reconciliationCandidates(db,owner,row.id)).entries).toEqual([]);
  const linked=(await db.get('transactions',entry.id))!;await expect(archiveEntry(db,owner,randomUUID(),entry.id,revision(linked),true)).rejects.toMatchObject({code:'LINKED_ENTRY'});
});
it('copies reviewed budgets, rejects stale reviews, removes limits reversibly and locks months against manual writes',async()=>{
  const first=await saveBudget(db,owner,randomUUID(),'2029-02',plan(),'');
  const preview=await copyPreview(db,owner,'2029-02');
  const copied=await saveBudget(db,owner,randomUUID(),'2029-03',{...preview,plan:{...preview.plan,limit:'90.00'}},'',true);
  expect((await loadPlanning(db,owner,'2029-03')).plan?.limit).toBe('90.00');
  const changed=await saveBudget(db,owner,randomUUID(),'2029-02',{...plan(),categories:[]},String(first.revision));
  expect((await loadPlanning(db,owner,'2029-02')).plan?.categories).toEqual([]);
  await expect(saveBudget(db,owner,randomUUID(),'2029-03',preview,String(copied.revision),true)).rejects.toMatchObject({code:'REVISION_CONFLICT'});
  await saveBudget(db,owner,randomUUID(),'2029-02',plan(),String(changed.revision));
  const state=await loadPlanning(db,owner,'2028-03'),close=await closeMonth(db,owner,randomUUID(),'2028-03',state.monthRevision,{action:'close'});
  await expect(generateMonth(db,owner,randomUUID(),'2028-03')).rejects.toMatchObject({code:'MONTH_CLOSED'});
  await expect(saveBudget(db,owner,randomUUID(),'2028-03',plan(),'')).rejects.toMatchObject({code:'MONTH_CLOSED'});
  const row=state.occurrences[0]!;await expect(changeOccurrence(db,owner,randomUUID(),row.id,row.revision,'postpone',{dueDate:'2028-04-01'})).rejects.toMatchObject({code:'MONTH_CLOSED'});
  await expect(saveEntry(db,owner,randomUUID(),{accountId:account,categoryId:category,description:'Mês fechado',amount:'1.00',kind:'expense',status:'recorded',purchaseDate:'2028-03-01',competenceMonth:'2028-03-01',dueDate:null,paidDate:null})).rejects.toMatchObject({code:'MONTH_CLOSED'});
  await closeMonth(db,owner,randomUUID(),'2028-03',String(close.revision),{action:'reopen'});expect((await loadPlanning(db,owner,'2028-03')).closed).toBe(false);
});
it('preserves closed and legacy paid months across future edits and rejects competing payment requests',async()=>{
  const input=ruleInput('2029-05',{endDate:'2029-08-31'}),saved=await saveRule(db,owner,randomUUID(),input);
  for(const month of ['2029-05','2029-06'])await generateMonth(db,owner,randomUUID(),month);
  const may=await occurrence('2029-05',String(saved.id));
  const results=await Promise.allSettled([1,2].map(()=>payOccurrence(db,owner,randomUUID(),may.id,may.revision,{amount:'100.00',paidDate:'2029-05-31'})));
  expect(results.filter(r=>r.status==='fulfilled')).toHaveLength(1);expect(results.filter(r=>r.status==='rejected')).toHaveLength(1);
  const original=await db.get('recurrenceOccurrences',may.id),state=await loadPlanning(db,owner,'2029-05');
  await closeMonth(db,owner,randomUUID(),'2029-05',state.monthRevision,{action:'close'});
  await expect(saveRule(db,owner,randomUUID(),{...input,fromMonth:'2029-04'},String(saved.id),String(saved.revision))).rejects.toMatchObject({code:'INVALID_START'});
  await expect(saveRule(db,owner,randomUUID(),{...input,fromMonth:'2029-05'},String(saved.id),String(saved.revision))).rejects.toMatchObject({code:'MONTH_CLOSED'});
  const changed=await saveRule(db,owner,randomUUID(),{...input,fromMonth:'2029-06',schedule:{...input.schedule,description:'Futura',amount:'120.00'}},String(saved.id),String(saved.revision));
  expect(await db.get('recurrenceOccurrences',may.id)).toEqual(original);
  expect(await occurrence('2029-06',String(saved.id))).toMatchObject({description:'Futura',amount:'120.00'});
  const june=await loadPlanning(db,owner,'2029-06');await closeMonth(db,owner,randomUUID(),'2029-06',june.monthRevision,{action:'close'});
  await expect(saveRule(db,owner,randomUUID(),input,String(saved.id),String(changed.revision))).rejects.toMatchObject({code:'MONTH_CLOSED'});
  const now=new Date(),legacyId=randomUUID(),legacyOccurrence=randomUUID();
  await db.put('recurrenceRules',{...input.schedule,id:legacyId,ownerId:owner,description:'Histórica',amount:'-20.00',currency:'BRL',startDate:'2027-01-01',endDate:null,archivedAt:null,createdAt:now,updatedAt:now});
  await db.put('recurrenceOccurrences',{id:legacyOccurrence,ownerId:owner,ruleId:legacyId,competenceMonth:'2027-01-01',dueDate:'2027-01-31',amount:'-20.00',status:'paid',createdAt:now,updatedAt:now});
  const legacy=(await db.get('recurrenceRules',legacyId))!;
  await saveRule(db,owner,randomUUID(),{...input,fromMonth:'2030-01',schedule:{...input.schedule,startDate:'2027-01-01',endDate:null,description:'Nova descrição'}},legacyId,revision(legacy));
  expect(await occurrence('2027-01',legacyId)).toMatchObject({description:'Histórica',amount:'20.00',status:'paid'});
});
it('protects both transfer competences and manual edits/deletion in closed months',async()=>{
  const destination=String((await saveAccount(db,owner,randomUUID(),{...accountInput,name:'Destino'})).id);
  const data={accountId:account,toAccountId:destination,categoryId:category,description:'Par legado',amount:'10.00',kind:'transfer',status:'settled',purchaseDate:'2030-01-10',competenceMonth:'2030-01-01',dueDate:null,paidDate:'2030-01-10'};
  const pair=await saveEntry(db,owner,randomUUID(),data),ids=pair.ids as string[],incoming=(await db.get('transactions',ids[1]!))!;
  await db.put('transactions',{...incoming,competenceMonth:'2030-02-01'});
  const state=await loadPlanning(db,owner,'2030-02');await closeMonth(db,owner,randomUUID(),'2030-02',state.monthRevision,{action:'close'});
  await expect(saveEntry(db,owner,randomUUID(),data,ids[0],String(pair.revision))).rejects.toMatchObject({code:'MONTH_CLOSED'});
  await expect(archiveEntry(db,owner,randomUUID(),ids[0]!,String(pair.revision),true)).rejects.toMatchObject({code:'MONTH_CLOSED'});
  expect((await db.get('transactions',ids[0]!))!.archivedAt).toBeNull();expect((await db.get('transactions',ids[1]!))!.competenceMonth).toBe('2030-02-01');
});
it('fails foreign schedules and owner injection atomically and restores all temporal metadata natively',async()=>{
  const before=await db.owned('recurrenceRules',owner,{order:[{field:'id',direction:'asc'}]});
  await expect(saveRule(db,owner,randomUUID(),ruleInput('2029-04',{accountId:foreign}))).rejects.toMatchObject({code:'NOT_FOUND'});
  await expect(saveRule(db,owner,randomUUID(),{...ruleInput('2029-04'),ownerId:other})).rejects.toThrow();
  expect(await db.owned('recurrenceRules',owner,{order:[{field:'id',direction:'asc'}]})).toEqual(before);
  const backup=await backupFirebase(db);await restoreFirebase(copy,backup);expect(await backupFirebase(copy)).toEqual(backup);
  await expect(exportPortableFirebase(db)).rejects.toThrow('schema v2');
});
